#!/usr/bin/env bash
#install nginx
sudo apt update
sudo apt -y install nginx
sudo service nginx start
sudo chown -R $USER:$USER  /var/www/html
# Nginx should be listening on port 80
# Done by default
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School
echo "Holberton School" > /var/www/html/index.nginx-debian.html