#!/usr/bin/env bash
#install nginx
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "/^\tserver_name localhost;/a location \/redirect_me \{\n\t\treturn 301 https://www.youtube.com/watch?v=$GUlwu4;\n\t\}"  /etc/nginx/sites-enabled/default
sudo service nginx reload