#!/usr/bin/env bash
#install nginx
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
echo "Holberton School" | sudo tee /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
      }
}
" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart